### ISSUE TITLE
May I ask which model "yolox_l_8x8_300e_coco.pth" is? The name of the page below is wrong

### ISSUE THREAD

**Issue by flyricci** [TMElyralab/Comfyui-MusePose#31]
May I ask which model "yolox_l_8x8_300e_coco.pth" is? The name of the page below is wrong

**Comment by TheRedheadedWitch** [comment]
I have the same issue, the file doesn't exist on that page and I keep getting an error at MUSEPOSEALIGN that the file isn't found, yet I can't find a location anywhere to download it. Your down page that references DWPOSE does not include the files that you say are needed in the DWPose folder so we need clarification on what we should do please.
