### ISSUE TITLE
requirements.txt Is it reasonable?

### ISSUE THREAD

**Issue by hben35096** [TMElyralab/Comfyui-MusePose#4]
one of them torch==2.0.1
Will this have a big impact on the ComfyUI running environment? Many people's running environment is Torch: 2.1.1

**Comment by lulu-xiao** [comment]
thanks for the comment. I tried and it works in torch 2.1.1.
Also I modified the version restrictions of torch and xformer. you can have a try.

**Comment by laidingq** [comment]
最重要的是diffusers的限制会和很多插件不兼容

**Comment by lulu-xiao** [comment]
> 最重要的是diffusers的限制会和很多插件不兼容

确实目前要求0.24.0的版本，是有点低了，后续我们看看是否可以升级下

**Comment by JPW0080** [comment]
On my side, it worked on Win 11 with Torch 2.2.2+cu121:
Unfortunately, diffusers==0.24.0 requirement did not agree with some Nodes.

![ComfyUI-MusePose-Torch-2-2-2+cu121](https://github.com/TMElyralab/Comfyui-MusePose/assets/104588046/32536b3d-3079-4903-add6-48ba568cf8df)

![ComfyUI-MusePose-Torch-2-2-2+cu121-xfomers](https://github.com/TMElyralab/Comfyui-MusePose/assets/104588046/9582f617-22fe-4be2-82e5-958aba8b278c)

FAILED IMPORT:

ComfyUI-Geowizard
ComfyUI-BrushNet
ComfyUI-layerdiffusion
ComfyUI-J
ComfyUI-ADMotionDirector

With luck, most of the other requirements should already be satisfied. 

After cloning, Backup and Delete everything within \ComfyUI\custom_nodes\Comfyui-MusePose\requirements.txt
The requiremnets.txt should now be empty...

Activate ComfyUI ENV

pip install diffusers==0.24.0
pip install openmim 
mim install mmengine 
mim install "mmcv==2.1.0"
mim install "mmdet==3.2.0" 
mim install "mmpose==1.3.1"

Launch ComfyUI and Test the provided musepose-workflow-demo workflow

If errors, refer to the backup of \ComfyUI\custom_nodes\Comfyui-MusePose\requirements.txt
Avoid anything Torch, xformers related.

Activate ComfyUI ENV and install missing requirements, like so
pip install av==11.0


Revert Diffusers Example

Activate ComfyUI ENV
pip install diffusers==0.27.2


OFFLINE diffusers Example

Download .whl
https://pypi.org/project/diffusers/0.24.0/#files
https://pypi.org/project/diffusers/0.27.2/#files

Place the diffusers .whls into something like \ComfyUI\whls

Activate ComfyUI ENV
cd \ComfyUI

pip install ./whls/diffusers-0.24.0-py3-none-any.whl

Revert diffusers OFFLINE

Activate ComfyUI ENV
cd \ComfyUI

pip install ./whls/diffusers-0.27.2-py3-none-any.whl

**Comment by Pythonpa** [comment]
> > 最重要的是diffusers的限制会和很多插件不兼容
> 
> 确实目前要求0.24.0的版本，是有点低了，后续我们看看是否可以升级下

对，这个版本确实有点低了，我目前找到一个临时解决办法，让diffusers==0.27.2也能先跑起来，虽然暂时没出现什么问题，但是如果官方能把这个依赖版本升高一点，当然最好。
![image](https://github.com/TMElyralab/Comfyui-MusePose/assets/16030016/fa5cabe9-3441-4cdc-aed3-b3e46f611957)

**Comment by Quasimondo** [comment]
Generally it would be nice if you could loosen some of those requirements and at least replace the == with >= - I understand that these are the versions which worked for you, but in practice most of the time those strict versions are not necessary and they tend to mess with other custom nodes that have to use the same system.

**Comment by Quasimondo** [comment]
Just in case it is interesting for others - I am able to run this without having to adhere to the strict version numbers - I removed all the == from the requirements.txt, so my file looks like this:

```
einops
imageio
imageio-ffmpeg
omegaconf
opencv-contrib-python
opencv-python
scikit-image
scikit-learn
transformers
mlflow
moviepy
urllib3
torch
torchdiffeq
torchmetrics
torchsde
torchvision
accelerate
av
clip
decord
diffusers
open-clip-torch
xformers
```

The only problem that occured is that two classes have been renamed in the newer diffusers library, but I was able to fix this by patching two files:

in unet_2d_condition.py:
replace all occurrences of "PositionNet" with "GLIGENTextBoundingboxProjection"

in transformer_2d.py:
replace all occurrences of "CaptionProjection" with "PixArtAlphaTextProjection"

**Comment by lulu-xiao** [comment]
> > > 最重要的是diffusers的限制会和很多插件不兼容
> > 
> > 
> > 确实目前要求0.24.0的版本，是有点低了，后续我们看看是否可以升级下
> 
> 对，这个版本确实有点低了，我目前想了一个临时解决办法，让diffusers==0.27.2也能先跑起来，虽然暂时没出现什么问题，但是如果官方能把这个依赖版本升高一点，当然最好。 ![image](https://private-user-images.githubusercontent.com/16030016/335798369-4ef21913-ba3d-4510-8195-3be7b5b9a5cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTQzNTgsIm5iZiI6MTcxNzI5NDA1OCwicGF0aCI6Ii8xNjAzMDAxNi8zMzU3OTgzNjktNGVmMjE5MTMtYmEzZC00NTEwLTgxOTUtM2JlN2I1YjlhNWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDAyMDczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMGJkNzQ3ZGM5NWNkOTE0MTFjNjRmMTc5N2M2OWZkNDliYzMyMjVhNjI4ZWE3OGRkMzJmZGRjOTZkMTNhZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1XzPp73jREiF5l5BfdKvKqQCf-tPxt1qIJjcOia0cAI)

diffusers 0.27.2 is now suported！

**Comment by lulu-xiao** [comment]
> On my side, it worked on Win 11 with Torch 2.2.2+cu121: Unfortunately, diffusers==0.24.0 requirement did not agree with some Nodes.
> 
> ![ComfyUI-MusePose-Torch-2-2-2+cu121](https://private-user-images.githubusercontent.com/104588046/335772807-32536b3d-3079-4903-add6-48ba568cf8df.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTQzNTgsIm5iZiI6MTcxNzI5NDA1OCwicGF0aCI6Ii8xMDQ1ODgwNDYvMzM1NzcyODA3LTMyNTM2YjNkLTMwNzktNDkwMy1hZGQ2LTQ4YmE1NjhjZjhkZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwMjA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTIyNDk2ODE4MzNhODMxNDRmODFhOGU5MTU5MzE1NGUzNzE3ZWFhNmUxZjQ1ZTcxZTE0MTgyNTFmMWY3NmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A6aVCwtqaG3kaLgMLZRjQV2KJqAJqmGAvOm0ZCSxGfg)
> 
> ![ComfyUI-MusePose-Torch-2-2-2+cu121-xfomers](https://private-user-images.githubusercontent.com/104588046/335772817-9582f617-22fe-4be2-82e5-958aba8b278c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTQzNTgsIm5iZiI6MTcxNzI5NDA1OCwicGF0aCI6Ii8xMDQ1ODgwNDYvMzM1NzcyODE3LTk1ODJmNjE3LTIyZmUtNGJlMi04MmU1LTk1OGFiYThiMjc4Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwMjA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Mjg1ZjM2YTBmNDk3NDNhODk4MDJkZGY0Y2RhMWY0ZmM5ZmMwYjViZmZiN2VlNWVlM2VkNWFhMjJlYjJjMmM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2GNuVTcEwEU0futpsaZm75oA27oa6LzAibflI8NuD1Y)
> 
> FAILED IMPORT:
> 
> ComfyUI-Geowizard ComfyUI-BrushNet ComfyUI-layerdiffusion ComfyUI-J ComfyUI-ADMotionDirector
> 
> With luck, most of the other requirements should already be satisfied.
> 
> After cloning, Backup and Delete everything within \ComfyUI\custom_nodes\Comfyui-MusePose\requirements.txt The requiremnets.txt should now be empty...
> 
> Activate ComfyUI ENV
> 
> pip install diffusers==0.24.0 pip install openmim mim install mmengine mim install "mmcv==2.1.0" mim install "mmdet==3.2.0" mim install "mmpose==1.3.1"
> 
> Launch ComfyUI and Test the provided musepose-workflow-demo workflow
> 
> If errors, refer to the backup of \ComfyUI\custom_nodes\Comfyui-MusePose\requirements.txt Avoid anything Torch, xformers related.
> 
> Activate ComfyUI ENV and install missing requirements, like so pip install av==11.0
> 
> Revert Diffusers Example
> 
> Activate ComfyUI ENV pip install diffusers==0.27.2
> 
> OFFLINE diffusers Example
> 
> Download .whl https://pypi.org/project/diffusers/0.24.0/#files https://pypi.org/project/diffusers/0.27.2/#files
> 
> Place the diffusers .whls into something like \ComfyUI\whls
> 
> Activate ComfyUI ENV cd \ComfyUI
> 
> pip install ./whls/diffusers-0.24.0-py3-none-any.whl
> 
> Revert diffusers OFFLINE
> 
> Activate ComfyUI ENV cd \ComfyUI
> 
> pip install ./whls/diffusers-0.27.2-py3-none-any.whl

**Comment by lulu-xiao** [comment]
> 最重要的是diffusers的限制会和很多插件不兼容

diffusers 0.27.2 is now suported

**Comment by laidingq** [comment]
> > 最重要的是diffusers的限制会和很多插件不兼容
> 
> diffusers 0.27.2 is now suported

已加载成功，谢谢
